# brew 'm-cli' # https://github.com/rgcr/m-cli/blob/master/Readme.md
brew 'ripgrep'
# brew 'diffuse' # for diffing 3+ files
cask 'emacs-app'  # installs emacsforosx.com emacs
brew 'coreutils'
brew 'fish'
brew 'git'
brew 'graphviz'
brew 'htop'
brew 'mtr'
brew 'nmap'
brew 'tmux'
brew 'fswatch' # for git-sync
cask 'nikitabobko/tap/aerospace'
cask 'firefox'
cask 'font-source-code-pro'
cask 'font-jetbrains-mono'
# cask 'libreoffice'
cask 'google-chrome'
