tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'd12frosted/emacs-plus'

# brew 'm-cli' # https://github.com/rgcr/m-cli/blob/master/Readme.md
brew 'ag'
# brew 'diffuse' # for diffing 3+ files
brew 'emacs-plus', args: ["with-modern-nuvola-icon"]
brew 'fish'
brew 'git'
brew 'graphviz'
brew 'htop'
brew 'mtr'
brew 'nmap'
brew 'tmux'
cask 'firefox'
cask 'font-source-code-pro'
cask 'font-jetbrains-mono'
cask 'iterm2'
# cask 'libreoffice'
cask 'google-chrome'
cask 'amethyst'
